// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCShfUeBwmcNm5NwdQfDgW_uL2Cvg2vnGE',
    appId: '1:694177376087:web:86832a5fbd249523db4012',
    messagingSenderId: '694177376087',
    projectId: 'whatsapp-messenger-a452a',
    authDomain: 'whatsapp-messenger-a452a.firebaseapp.com',
    storageBucket: 'whatsapp-messenger-a452a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeeyvB5DjYE4rPoRr_pY4xm_gZCJkc5Cw',
    appId: '1:694177376087:android:3d6fe78a3aab23ecdb4012',
    messagingSenderId: '694177376087',
    projectId: 'whatsapp-messenger-a452a',
    storageBucket: 'whatsapp-messenger-a452a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAiRAs2LMjj98YBuGw2v-j4vfRObLgR3o',
    appId: '1:694177376087:ios:2e0104e81e0bb28fdb4012',
    messagingSenderId: '694177376087',
    projectId: 'whatsapp-messenger-a452a',
    storageBucket: 'whatsapp-messenger-a452a.appspot.com',
    iosBundleId: 'com.example.whatappMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAiRAs2LMjj98YBuGw2v-j4vfRObLgR3o',
    appId: '1:694177376087:ios:dc97abafa17910cddb4012',
    messagingSenderId: '694177376087',
    projectId: 'whatsapp-messenger-a452a',
    storageBucket: 'whatsapp-messenger-a452a.appspot.com',
    iosBundleId: 'com.example.whatappMessenger.RunnerTests',
  );
}
